Updated strings to match with current version
HemmeligOrg/Hemmelig.app pull request #101
Opened 2022-09-28 13:04 UTC by RainerZufahl

Copied and translated strings (and string order) from commit `220b291` to match with #90.

Side Note: maybe we should have some kind of version system, so we can easily tell when string tables are outdated?

2022-09-28 21:23 UTC, casperklein requested changes

2022-09-28 21:23 UTC, casperklein commented on public/locales/de/translation.json
> +        "please_add_secret": "Bitte notiere hier ein Geheimnnis.",
```suggestion
        "please_add_secret": "Bitte notiere hier ein Geheimnis.",
```

2022-09-29 15:21 UTC, bjarneo commented
Thank you! I don't understand german, so I guess I will just go a head and merge it. Thanks for this PR!

2022-09-29 15:21 UTC, bjarneo approved these changes

2022-09-29 15:21 UTC, merged

2022-09-29 15:25 UTC, bjarneo commented
> Side Note: maybe we should have some kind of version system, so we can easily tell when string tables are outdated?

Any suggestions?